---
abstract: 'A little bit Extra on top of Test::MockObject'
author:
  - 'Sam Crawley <mutant.nz@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101241'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-MockObject-Extra
recommends: {}
requires:
  Test::MockObject: 1.09
version: 0.001
